//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateAdsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public Ad()
        {
            this.CompletedAdProfits = new HashSet<CompletedAdProfit>();
        }
    
        public int AdId { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime PostDate { get; set; }
        public int CityId { get; set; }
        public int CategoryId { get; set; }
        public int AdTypeId { get; set; }
        public int StatusId { get; set; }
        public decimal Price { get; set; }
    
        public virtual AdType AdType { get; set; }
        public virtual Category Category { get; set; }
        public virtual City City { get; set; }
        public virtual AdStatus AdStatus { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<CompletedAdProfit> CompletedAdProfits { get; set; }
    }
}
