//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateAdsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdStatus
    {
        public AdStatus()
        {
            this.Ads = new HashSet<Ad>();
        }
    
        public int StatusId { get; set; }
        public string StatusName { get; set; }
    
        public virtual ICollection<Ad> Ads { get; set; }
    }
}
