//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateAdsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompletedAdProfit
    {
        public int ProfitId { get; set; }
        public int AdId { get; set; }
        public decimal ProfitAmount { get; set; }
    
        public virtual Ad Ad { get; set; }
    }
}
